### ISSUE TITLE
How Did You Implement Socket Communication?

### ISSUE THREAD

**Issue by ljwoon** [potatocs-ce/potatocs-ce-collab-server#3]
I used the socket.io module on the server, but it seems like the communication is not working properly.

**Comment by potatocs-ce** [comment]
Currently, we are not using socket communication in potatocs-ce-collab-server.
 
It is being utilized in potatocs-ce-meeting-server and potatocs-ce-meeting-server.
 
 Please double-check the paths, files, and ports.

**Comment by potatocs-ce** [comment]
https://www.mkdocs.org/
